config/routes.rb
Rails.application.routes.draw do

  root to: 'cocktails#index'
  
  get 'ingredients/new'
  get 'ingredients/create'



  resources :cocktails do
    resources :doses, only: [:new, :create, :destroy]
  end

  resources :doses, only: [] do
    resources :ingredients, only: [:new, :create]
  end

  resources :doses, only: :destroy
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cocktail.rb
class Cocktail < ApplicationRecord
  has_many :doses, dependent: :destroy
  has_many :ingredients, through: :doses
  has_one_attached :photo
  validates :name, uniqueness: true
  validates :name, presence: true
end

app/models/dose.rb
class Dose < ApplicationRecord
  belongs_to :cocktail
  belongs_to :ingredient
  validates :description, presence: true
  validates_uniqueness_of :cocktail, :scope => [:ingredient]
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
  has_many :doses
  validates :name, uniqueness: true
  validates :name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/cocktails_controller.rb
class CocktailsController < ApplicationController
  before_action :set_cocktail, only: %i[ show edit destroy]

  def index
    @cocktails = Cocktail.all
  end

  def show
  end

  def new
    @cocktail = Cocktail.new    
  end

  def edit
  end
  
  def create
    @cocktail = Cocktail.new(cocktail_params)

    if @cocktail.save
      redirect_to @cocktail, notice: 'Cocktail successfully created'
    else
      render :new
    end
  end

  def destroy
    @cocktail.destroy
  end

  
  private

  def set_cocktail
    @cocktail = Cocktail.find(params[:id])
  end
  

  def cocktail_params
    params.require(:cocktail).permit(:name, :photo) 
  end
end

app/controllers/doses_controller.rb
class DosesController < ApplicationController
  def new
    @dose = Dose.new # this is for the form
    @cocktail = Cocktail.find(params[:cocktail_id]) # this is for the form
  end

  def create
    @dose = Dose.new(description: params[:dose][:description])
    @cocktail = Cocktail.find(params[:cocktail_id]) # this is for the form
    @ingredient = Ingredient.find(params[:dose][:ingredient])
    @dose.cocktail = @cocktail
    @dose.ingredient = @ingredient
    if @dose.save!
      redirect_to cocktail_path(@cocktail.id)
    else
      render :new #.html.erb
    end
  end

  def destroy
    @dose = Dose.find(params[:id])
    @dose.destroy # from the DB. The @dose is still here in the RAM
    @cocktail = @dose.cocktail
    redirect_to cocktail_path(@cocktail.id)
  end

  private

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cocktails_helper.rb
module CocktailsHelper
end

app/helpers/doses_helper.rb
module DosesHelper
end

app/views/cocktails/_form.html.erb
<%= simple_form_for(cocktail) do |f| %>
  <%= f.input :name %>
  <%= f.input :photo, as: :file %>
  <%= f.submit %>
<% end %>

app/views/cocktails/edit.html.erb
<h1>TO DO</h1>

app/views/cocktails/index.html.erb
<div class="container">

  <div class="d-flex flex-row justify-content-between m-3">
    <h1>Mister Cocktail</h1>
    <div class="p-2"><%= link_to 'New Cocktail', new_cocktail_path, class: 'btn btn-primary' %></div>
  </div>

  <div class="d-flex justify-content-center">
    <div class="container">
      <div class="row">
        <% @cocktails.each do |cocktail| %>
          <div class="card" style="width: 18rem;">
            <img class="card-img-top" src="<%= cl_image_path cocktail.photo.key, height: 300, width: 400, crop: :fill %>" alt="Card image cap">
            <div class="card-body">
              <h5 class="card-title"><%= cocktail.name %></h5>
            </div>
            <ul class="list-group list-group-flush">
              <% cocktail.doses.first(3).each do |dose| %> 
                <li class="list-group-item">
                  <%= dose.description %>
                  <strong><%= dose.ingredient.name %></strong>
                </li>
              <% end %>
                <li class="list-group-item"><strong><%= link_to '...', cocktail %></strong></li>
            </ul>
              <div class="card-body d-flex justify-content-between">
                <%= link_to 'Show', cocktail %>
                <%= link_to cocktail, method: :delete do %>
                  <i class="fa fa-trash"></i>
                <% end %>
                
              </div>
          </div>
        <% end %>
      </div>
    </div>
  </div>

  <div class="container">
    
  </div>

</div>

app/views/cocktails/new.html.erb
  
<h1>New Cocktail</h1>

<%= render 'form', cocktail: @cocktail %>

<%= link_to 'Back', cocktails_path %>

app/views/cocktails/show.html.erb
<div class="container mt-3">

   <div class="d-flex flex-row justify-content-end">
     <h1 class="p-2"><%= @cocktail.name %></h1>
     <div class="p-2"><%= link_to 'Add a Dose', new_cocktail_dose_path(@cocktail), class: 'btn btn-primary' %></div>
     <div class="p-2 flex-grow-1"><%= link_to 'Edit Cocktail', edit_cocktail_path(@cocktail), class: 'btn btn-primary' %></div>
     <div class="p-2"><%= link_to 'See All Cocktails', cocktails_path, class: 'btn btn-primary' %></div>
   </div>

<br>

   <h3>How to make it...</h3>
      <table class="table">
        <tbody>
          <thead>
            <th>Ingredient</th>
            <th>Description</th>
            <th>Action</th>
          </thead>
          <% @cocktail.doses.each do |dose| %>
            <tr>
              <td><%= dose.description %>...</td>
              <td><%= dose.ingredient.name %></td>
              <td>
                <%= link_to dose_path(dose), method: :delete, data: { confirm: "Are you sure?" } do %>
                  <i class="fa fa-trash destroy_dose"></i>
                <% end %>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
</div>

<div class="d-flex justify-content-center">
  <div><%= cl_image_tag @cocktail.photo.key, height: 300, width: 400, crop: :fill, class: "cocktail-main-image" %></div>
</div>

app/views/doses/new.html.erb
<%= simple_form_for [@cocktail, @dose] do |f| %>
  <%= f.input :description %>
  <%= f.input :ingredient, collection: Ingredient.all, input_html: {  class: 'multiple-select', multiple: false }, include_hidden: false %>
  <%= f.submit %>
<% end %>

app/views/ingredients/new.html.erb
<div class="container">
  <div class="row justify-content-center">
    <div class="col-12 col-md-8">
      <h1>Add new ingredient.</h1>

      <%= simple_form_for [ @dose, @ingredient ] do |f| %>
        <%= f.input :ingredient, collection: Ingredient.all, input_html: {  class: 'multiple-select', multiple: true }, include_hidden: false %>
        <%= f.submit "Select ingredient", class: 'btn btn-primary' %>
      <% end %>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <title>RailsMisterCocktail</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>